name: Build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install build-essential cmake 

    - name: Build tests
      run: cd test
      run: cmake -B build
      run: cmake --build build -j

    - name: Test
      run: cd build && make test
