name: Build and test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt install build-essential cmake 

    - name: Build tests
      working-directory: ./test
      run: |
        cmake -B build
        cmake --build build -j

    - name: Test
      working-directory: ./test/build
      run: make test
